
environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37-x64"

install:
    - ps: Install-Product node 10  # Provide access to npm
    - python -m pip install pipenv
    - pipenv install --dev

build: false

test_script:
    - ps: pipenv run python dev.py test --python $env:PYTHON
