
environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37-x64"

install:
    - python -m pip install pipenv
    - pipenv install --dev

build: off

test_script:
    - pipenv run python dev.py test
