
environment:
    matrix:
        - PYTHON: '3.6'
        - PYTHON: '3.7'

install:
    # NOTE --disable-pip-version-check needed to prevent unnecessary failure
    - ps: python -m pip --disable-pip-version-check install pipenv
    - ps: pipenv --python $env:PYTHON
    - ps: pipenv install --dev

build: false

test_script:
    - ps: pipenv run python dev.py test --python $env:PYTHON
