
environment:
    matrix:
        - {PYTHON: "C:\\Python36-x64", PYTHON_VERSION: "3.6"}
        - {PYTHON: "C:\\Python37-x64", PYTHON_VERSION: "3.7"}

install:
    - python -m pip install pipenv
    - pipenv install --dev

build: false

test_script:
    - ps: pipenv run python dev.py test --python $env:PYTHON_VERSION
