
environment:
    matrix:
        - PYTHON: '3.6'  # Oldest version supported
        - PYTHON: '3.7'  # Newest version supported
        - {PYTHON: '3.7', UPDATE: 'y'}  # Newest version and dependencies

# WARN Avoid powershell as it fails if anything written to stderr (even if success)
#   pip and pipenv do this with warnings etc
install:
    - python -m pip --disable-pip-version-check install pipenv
    - pipenv --python %PYTHON%
    # Diff platforms require diff deps (e.g. pytest-cov) so must recreate lock file
    # TODO Stop this from upgrading all packages when possible (https://git.io/fAzzE)
    # Oldest and latest deps still tested in Travis, so not a big deal
    - pipenv lock --dev
    # - if "%UPDATE%" == "y" (pipenv update) TODO Happens always until above fixed
    - pipenv sync --dev
    - pipenv graph  # For debugging's sake

build: false

test_script:
    - pipenv run python dev.py test --python %PYTHON%
