
os: linux
dist: xenial
language: python

matrix:
    include:
      - python: 3.6
      # 3.7 requires sudo for some reason
      - python: 3.7
        sudo: true
      # OSX doesn't support diff python versions yet so must manually install
      - os: osx
        language: generic
        env: PYTHON="3.6"
      - os: osx
        language: generic
        env: PYTHON="3.7"

before_install: |
    # OSX specific requirements
    if test $TRAVIS_OS_NAME == osx; then
        pyenv install $PYTHON  # Install required python version
        pyenv global $PYTHON  # Switch to new version
        sudo npm install --global npm  # Travis' version doesn't support lock files
    fi
    # Need pipenv for install
    python -m pip install pipenv

install: pipenv install --dev

script: pipenv run python dev.py test
