
os: linux
dist: xenial
language: python

matrix:
    include:
      - python: '3.6.0'
      # 3.7 requires sudo for some reason
      - python: '3.7.0'
        sudo: true
      # OSX doesn't support diff python versions yet so must manually install
      # NOTE Using TRAVIS_PYTHON_VERSION so same variable name when used in `script`
      - os: osx
        language: generic
        env: TRAVIS_PYTHON_VERSION="3.6.0"  # NOTE pyenv requires all three parts
      - os: osx
        language: generic
        env: TRAVIS_PYTHON_VERSION="3.7.0"

before_install: |
    # OSX specific requirements
    if test $TRAVIS_OS_NAME == osx; then
        if test $TRAVIS_PYTHON_VERSION == "3.7.0"; then
            brew upgrade pyenv  # Old version doesn't know about Python 3.7
        fi
        pyenv install $TRAVIS_PYTHON_VERSION  # Install required python version
        pyenv global $TRAVIS_PYTHON_VERSION  # Switch to new version
        sudo npm install --global npm  # Travis' version doesn't support lock files
    fi
    # Need pipenv for install
    python -m pip install pipenv

install: |
    pipenv --python $TRAVIS_PYTHON_VERSION
    pipenv install --dev

script: pipenv run python dev.py test --python $TRAVIS_PYTHON_VERSION
