
os: linux
dist: xenial
language: python

# OSX doesn't support python yet so need to give custom setup via matrix instead
matrix:
    include:
      - python: 3.6
      - python: 3.7
        sudo: true
      - os: osx
        language: generic
        env: PYTHON="3.6"
      - os: osx
        language: generic
        env: PYTHON="3.7"

before_install: |
    if test $TRAVIS_OS_NAME == osx; then
        pyenv install $PYTHON
        pyenv global $PYTHON
        sudo npm install --global npm
    fi
    python -m pip install pipenv

install: pipenv install --dev

script: pipenv run python dev.py test
